### PR TITLE
Feature augmentation

### PR DESCRIPTION
**Pull request by priestjim**
Where should I begin :) Seriously augmented the capabilities of the script by:
- adding a numeric rotation interval (ie. keep the last 7 backups) in order to be able to run it via a rundeck job
- added a specific devices option in order to be able to select exactly the devices you may need snapshotted
- added pending snapshots check
- added automatic region detection
- updated lots of stuff in the script logic
- added a maintenance only option in order to only rotate (no snapshots)
- added fsfreeze support for newer kernels (but skip freezing / because it's dangerous and the system may not recover without a reboot)
- bumped the gem version to 0.2

### CODE REVIEW

**Comment by jedateach** [comment]
Is this gem still used/maintained? Or is there a better option about?

**Comment by priestjim** [comment]
I still maintain my fork, you can use that one if you wish!

**Comment by jedateach** [comment]
Great thanks... how would I use your version via rubygems?

**Comment by priestjim** [comment]
git clone ...
cd ec2-snapshot
rake install

**Comment by jedateach** [comment]
ah, ok. Thank you.

I'm a php dev / ruby newbie.

**Pull request closed without merging**
